apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-npc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hattmo/applied_project_cluster.git
    targetRevision: HEAD
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-npc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
